# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4d0574b77953f41734a6b07fa63da7a2ad7f44ae59f38e0112a7dbfc343a1d7c62668ab47a36d277390b614989be5c12f84f9fe9248294ffe769de3a968b8c8

test:
  secret_key_base: a076f44f291389fe66c4153fd6fcaf2e4532f8a4be17a11ac623b9079a096c2cc2a121d63fd9e8552eea2edabbe5f72184a5020c3d64d11bed892a444da6baad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: a076f44f291389fe66c4153fd6fcaf2e4532f8a4be17a11ac623b9079a096c2cc2a121d63fd9e8552eea2edabbe5f72184a5020c3d64d11bed892a444da6baad
  secret_key_base: a076f44f291389fe66c4153fd6fcaf2e4532f8a4be17a11ac623b9079a096c2cc2a121d63fd9e8552eea2edabbe5f72184a5020c3d64d11bed892a444da6baad
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
